language: node_js
node_js:
  - 8
  - 10
  - 12
  - node
os:
  - linux
  - windows

install:
    - npm ci
script:
  # Make sure the code is good
  - npm run lint
  # and it builds
  - npm run build
  # Now perform a test run
  - npm test
  # TODO: No actual tests aside from declaration checks

notifications:
    email: false
